"""
Unit and API Integration Tests for GapGuard AI Manuscript Text Extraction Foundation.
Tests PDF, DOCX, and TXT extraction for:
- Valid documents
- Empty documents
- Corrupted documents
- Unsupported file types
- Character and word count accuracy
- FastAPI endpoint POST /api/manuscripts/extract-text
"""

import io
import sys
import unittest
from pathlib import Path

# Add backend directory to sys.path
BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from docx import Document
from fastapi.testclient import TestClient

from main import app
from services.manuscript_extractor import (
    extract_manuscript_text,
    extract_text_from_pdf,
    extract_text_from_docx,
    extract_text_from_txt,
)


def create_valid_docx_bytes(paragraphs=None) -> bytes:
    """Helper to generate a valid in-memory DOCX document."""
    doc = Document()
    if paragraphs is None:
        paragraphs = [
            "Explainable Contrastive Learning for Multi-Modal Medical Diagnostics.",
            "Attribution maps generated by deep neural networks frequently exhibit spurious correlation artifacts.",
            "Our proposed methodology grounds patch tokens directly to clinical concepts.",
        ]
    for p in paragraphs:
        doc.add_paragraph(p)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def create_valid_pdf_bytes(text_snippet="GapGuard AI Research Manuscript") -> bytes:
    """Helper to generate a minimal valid standard PDF 1.4 byte stream with correct xref offsets."""
    content = f"BT /F1 12 Tf 50 700 Td ({text_snippet}) Tj ET".encode("latin-1")
    objects = [
        b"",  # 0 is dummy
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
        b"4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
        f"5 0 obj\n<< /Length {len(content)} >>\nstream\n".encode("latin-1") + content + b"\nendstream\nendobj\n",
    ]
    header = b"%PDF-1.4\n"
    offsets = [0]
    curr = len(header)
    for obj in objects[1:]:
        offsets.append(curr)
        curr += len(obj)
    xref_offset = curr
    xref = f"xref\n0 {len(objects)}\n0000000000 65535 f \n".encode("latin-1")
    for off in offsets[1:]:
        xref += f"{off:010d} 00000 n \n".encode("latin-1")
    trailer = f"trailer\n<< /Size {len(objects)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("latin-1")
    return header + b"".join(objects[1:]) + xref + trailer


def create_empty_pdf_bytes() -> bytes:
    """Helper to generate a PDF with no extractable text."""
    objects = [
        b"",
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> >>\nendobj\n",
    ]
    header = b"%PDF-1.4\n"
    offsets = [0]
    curr = len(header)
    for obj in objects[1:]:
        offsets.append(curr)
        curr += len(obj)
    xref_offset = curr
    xref = f"xref\n0 {len(objects)}\n0000000000 65535 f \n".encode("latin-1")
    for off in offsets[1:]:
        xref += f"{off:010d} 00000 n \n".encode("latin-1")
    trailer = f"trailer\n<< /Size {len(objects)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("latin-1")
    return header + b"".join(objects[1:]) + xref + trailer


class TestManuscriptExtractionService(unittest.TestCase):
    """Unit tests for the manuscript_extractor service functions."""

    def test_extract_txt_valid(self):
        sample_txt = (
            "Title: Graph Representation Learning\n\n"
            "Abstract: We propose an adaptive graph convolution layer.\n\n"
            "Methodology: Laplacian smoothing with residual connections."
        ).encode("utf-8")

        result = extract_manuscript_text(sample_txt, "study.txt")
        self.assertTrue(result["success"])
        self.assertEqual(result["file_type"], "TXT")
        self.assertIn("adaptive graph convolution layer", result["text"].lower())
        self.assertEqual(result["character_count"], len(result["text"]))
        self.assertEqual(result["word_count"], len(result["text"].split()))

    def test_extract_txt_empty(self):
        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(b"   \n\n   ", "empty.txt")
        self.assertIn("empty", str(ctx.exception).lower())

    def test_extract_docx_valid(self):
        docx_bytes = create_valid_docx_bytes([
            "Section 1: Introduction",
            "This paper studies low-resource dialect translation.",
            "Our model uses cross-lingual anchors.",
        ])

        result = extract_manuscript_text(docx_bytes, "paper.docx")
        self.assertTrue(result["success"])
        self.assertEqual(result["file_type"], "DOCX")
        self.assertIn("Section 1: Introduction", result["text"])
        self.assertIn("cross-lingual anchors", result["text"])
        self.assertGreater(result["word_count"], 10)

    def test_extract_docx_empty(self):
        doc = Document()
        buf = io.BytesIO()
        doc.save(buf)
        empty_docx = buf.getvalue()

        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(empty_docx, "empty.docx")
        self.assertIn("empty", str(ctx.exception).lower())

    def test_extract_docx_corrupted(self):
        corrupted_bytes = b"PK\x03\x04corrupted-binary-garbage-not-a-valid-zip-archive"
        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(corrupted_bytes, "broken.docx")
        self.assertIn("corrupted", str(ctx.exception).lower())

    def test_extract_pdf_valid(self):
        pdf_bytes = create_valid_pdf_bytes("Novelty Differentiation and Gap Analysis")
        result = extract_manuscript_text(pdf_bytes, "manuscript.pdf")

        self.assertTrue(result["success"])
        self.assertEqual(result["file_type"], "PDF")
        self.assertIn("Novelty Differentiation", result["text"])
        self.assertGreater(result["character_count"], 10)

    def test_extract_pdf_empty(self):
        empty_pdf = create_empty_pdf_bytes()
        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(empty_pdf, "scanned_or_empty.pdf")
        self.assertIn("no readable text", str(ctx.exception).lower())

    def test_extract_pdf_corrupted(self):
        corrupted_pdf = b"not-a-pdf-header-junk-bytes"
        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(corrupted_pdf, "corrupted.pdf")
        self.assertIn("valid pdf", str(ctx.exception).lower())

    def test_unsupported_extension(self):
        with self.assertRaises(ValueError) as ctx:
            extract_manuscript_text(b"some content", "binary.exe")
        self.assertIn("unsupported file format", str(ctx.exception).lower())


class TestManuscriptExtractionAPI(unittest.TestCase):
    """Integration tests for POST /api/manuscripts/extract-text."""

    def setUp(self):
        self.client = TestClient(app)

    def test_api_extract_txt_success(self):
        content = "Research Question: Can self-supervision resolve domain shift?\n\nYes, it can."
        files = {"file": ("hypothesis.txt", io.BytesIO(content.encode("utf-8")), "text/plain")}

        response = self.client.post("/api/manuscripts/extract-text", files=files)
        self.assertEqual(response.status_code, 200)

        data = response.json()
        self.assertTrue(data["success"])
        self.assertEqual(data["file_name"], "hypothesis.txt")
        self.assertEqual(data["file_type"], "TXT")
        self.assertIn("Can self-supervision resolve domain shift?", data["text"])
        self.assertEqual(data["word_count"], 10)

    def test_api_extract_docx_success(self):
        docx_bytes = create_valid_docx_bytes(["Empirical Evaluation of Federated Models."])
        files = {
            "file": (
                "evaluation.docx",
                io.BytesIO(docx_bytes),
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )
        }

        response = self.client.post("/api/manuscripts/extract-text", files=files)
        self.assertEqual(response.status_code, 200)

        data = response.json()
        self.assertTrue(data["success"])
        self.assertEqual(data["file_type"], "DOCX")
        self.assertIn("Federated Models", data["text"])

    def test_api_extract_pdf_success(self):
        pdf_bytes = create_valid_pdf_bytes("Clinical Diagnostic Validation Pipeline")
        files = {"file": ("clinical_study.pdf", io.BytesIO(pdf_bytes), "application/pdf")}

        response = self.client.post("/api/manuscripts/extract-text", files=files)
        self.assertEqual(response.status_code, 200)

        data = response.json()
        self.assertTrue(data["success"])
        self.assertEqual(data["file_type"], "PDF")
        self.assertIn("Clinical Diagnostic Validation", data["text"])

    def test_api_unsupported_file_type_rejected(self):
        files = {"file": ("code.py", io.BytesIO(b"print('hello')"), "text/x-python")}
        response = self.client.post("/api/manuscripts/extract-text", files=files)

        self.assertEqual(response.status_code, 400)
        self.assertIn("unsupported file format", response.json().get("detail", "").lower())

    def test_api_empty_file_rejected(self):
        files = {"file": ("empty.txt", io.BytesIO(b""), "text/plain")}
        response = self.client.post("/api/manuscripts/extract-text", files=files)

        self.assertEqual(response.status_code, 400)
        self.assertIn("empty", response.json().get("detail", "").lower())

    def test_api_corrupted_docx_rejected(self):
        files = {
            "file": (
                "bad.docx",
                io.BytesIO(b"junk-bytes"),
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )
        }
        response = self.client.post("/api/manuscripts/extract-text", files=files)

        self.assertEqual(response.status_code, 400)
        self.assertIn("corrupted", response.json().get("detail", "").lower())


if __name__ == "__main__":
    unittest.main()
